### ISSUE TITLE
MsgTimeoutException 问题

### ISSUE THREAD

**Issue by crossoverJie** [linzhaoming/easyframe-msg#1]
你好，在使用while循环判断是否还有下一条消息的是抛出`MsgTimeoutException`。

# 前提条件
kafka几个小时甚至更长时间没有数据，消费者也就很久没有消费过，突然生产一些数据就会偶尔出现以上连接超时异常。

重启消费者就可以正常消费了。

谢谢。

https://github.com/linzhaoming/easyframe-msg/blob/eabe66c5d80b1e4a5f6a32964990ff2b3d64bc4e/src/main/java/com/easyfun/easyframe/msg/MsgIterator.java#L21-L28

**Comment by linzhaoming** [comment]
这个版本基于Kafka的老API。目前现在已经不再维护。建议使用Spring Kafka进行访问

**Comment by crossoverJie** [comment]
@linzhaoming 已经换回官方消费可以了 谢谢
